from typing import Protocol

from rusoft.domain.entities import Product, ProductId, ProductImage


class ProductRepository(Protocol):

    async def add_products(self, products: list[Product]) -> list[Product]: ...

    async def remove_all_products(self) -> bool: ...

    async def replace_products(self, products: list[Product]) -> list[Product]: ...

    async def add_image(self, product_id: ProductId, image: ProductImage) -> Product: ...

    async def is_empty(self) -> bool: ...

    async def get_all_products(self) -> list[Product]: ...